      - name: Download Android ARM64 JRE 17
        run: |
          mkdir -p source/app_pojavlauncher/src/main/assets/components/jre-new

          curl -fL --retry 3 \
            -o jre17.tar.xz \
            "https://github.com/AngelAuraMC/angelauramc-openjdk-build/releases/download/release/jre17-android-arm64.tar.xz"

          tar -xJf jre17.tar.xz \
            -C source/app_pojavlauncher/src/main/assets/components/jre-new \
            --strip-components=1

          rm jre17.tar.xz

      - name: Download Android ARM64 JRE 21
        run: |
          mkdir -p source/app_pojavlauncher/src/main/assets/components/jre-21

          curl -fL --retry 3 \
            -o jre21.tar.xz \
            "https://github.com/AngelAuraMC/angelauramc-openjdk-build/releases/download/release/jre21-android-arm64.tar.xz"

          tar -xJf jre21.tar.xz \
            -C source/app_pojavlauncher/src/main/assets/components/jre-21 \
            --strip-components=1

          rm jre21.tar.xz
